# Generated by Django 5.2.15 on 2026-06-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='department',
        ),
    ]
